name: 'Check PR Title'
description: 'Check PR title is correct'
inputs:
  repo-token:
    description: 'The GITHUB_TOKEN secret'
    required: true
  jira-token:
    description: 'JIRA token'
    required: true
  jira-user:
    description: 'JIRA username'
    required: true
runs:
  using: 'node12'
  main: 'index.js'
